export const CHANGE_NAME = "CHANGE_NAME";
export const ADD_WISH = "ADD_WISH";
export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED";
export const GET_ITEMS_SUCCEEDED = "GET_ITEMS_SUCCEEDED";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";