// Get Items

export const GET_ITEMS_STARTED = "GET_ITEMS_STARTED";
export const GET_ITEMS_SUCCEEDED = "GET_ITEMS_SUCCEEDED";
export const GET_ITEMS_FAILED = "GET_ITEMS_FAILED";

// Add to Cart

export const ADD_TO_CART_ITEM_STARTED = "ADD_TO_CART_ITEM_STARTED";
export const ADD_TO_CART_ITEM_SUCCEEDED = "ADD_TO_CART_ITEM_SUCCEEDED";
export const ADD_TO_CART_ITEM_FAILED = "ADD_TO_CART_ITEM_FAILED";

// Remove Cart
export const REMOVE_TO_CART_ITEM_STARTED = "REMOVE_TO_CART_ITEM_STARTED";
export const REMOVE_TO_CART_ITEM_SUCCEEDED = "REMOVE_TO_CART_ITEM_SUCCEEDED";
export const REMOVE_TO_CART_ITEM_FAILED = "REMOVE_TO_CART_ITEM_FAILED";

// Get Product Type
export const GET_PRODUCT_TYPE_STARTED = "GET_PRODUCT_TYPE_STARTED";
export const GET_PRODUCT_TYPE_SUCCEEDED = "GET_PRODUCT_TYPE_SUCCEEDED";
export const GET_PRODUCT_TYPE_FAILED = "GET_PRODUCT_TYPE_FAILED";

// Get Item Details
export const GET_ITEM_DETAIL_STARTED = "GET_ITEM_DETAIL_STARTED";
export const GET_ITEM_DETAIL_SUCCEEDED = "GET_ITEM_DETAIL_SUCCEEDED";
export const GET_ITEM_DETAIL_FAILED = "GET_ITEM_DETAIL_FAILED";
